version: '3'
services:
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bin/rails s -p 3000 -b '0.0.0.0'"
    command: bin/setup
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      # db:
        # condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_development
      RAILS_ENV: development
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
